Remove unused variable
New clang detects this unused variable.

https://ci.chromium.org/p/chromium/builders/luci.chromium.try/ios-device/4574
../../ios/chrome/browser/browser_state/chrome_browser_state_io_data.mm:86:7: error: unused variable 'iter' [-Werror,-Wunused-variable]
      iter;
      ^
1 error generated.

Cq-Include-Trybots: luci.chromium.try:ios-simulator-full-configs;master.tryserver.chromium.mac:ios-simulator-cronet
Change-Id: I019c3ecf8677e4b93f8289a722686bc186476bfe
Reviewed-on: https://chromium-review.googlesource.com/1143172
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Rohit Rao <rohitrao@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#576443}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: df95356eeb6cf5ad52e850894b3491e10d9d1ec9