Revert of Refine the accessibility label of Clear Browsing Data flow. (patchset #2 id:20001 of https://codereview.chromium.org/2750403002/ )
Reason for revert:
Caused a variety of EG test failures.
For example:
SettingsTestCase.testClearPasswords
SettingsTestCase.testClearPasswords:
../../ios/chrome/browser/ui/settings/settings_egtest.mm:294: error: -[SettingsTestCase testClearPasswords] : Exception: NoMatchingElementException

Exception Name: NoMatchingElementException
Exception Reason: Cannot find UI element.
Exception with Action: {
  "Action Name" : "Tap",
  "Element Matcher" : "((((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityLabel('Clear Browsing Data')) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityTraits: UIAccessibilityTraitButton)) && !kindOfClass('MDCCollectionViewTextCell'))",
  "Recovery Suggestion" : "Check if element exists in the UI, modify assert criteria, or adjust the matcher"
}

Original issue's description:
> Refine the accessibility label of Clear Browsing Data flow.
>
> When using VoiceOver, the user taps a button to Clear Browsing Data then
> gets on a new Clear Browsing Data button, which can be confusing.
> To make it more understandable, this CL changes the accessibility label
> of the second button to "Confirm Clear Browsing Data".
>
> BUG=688415
> R=lindsayw@chromium.org
>
> Review-Url: https://codereview.chromium.org/2750403002
> Cr-Commit-Position: refs/heads/master@{#458186}
> Committed: https://chromium.googlesource.com/chromium/src/+/cf84fa5c1519b0d0867d49071d3266004605d53b

TBR=lindsayw@chromium.org,noyau@chromium.org,olivierrobin@chromium.org,lpromero@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=688415

Review-Url: https://codereview.chromium.org/2763793002
Cr-Original-Commit-Position: refs/heads/master@{#458234}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: b1cb679f18cefc5699f848827ba9b94751ec898c