Revert of Use IOSImageDataFetcherWrapper for favicon (patchset #9 id:160001 of https://codereview.chromium.org/2677993002/ )
Reason for revert:
A compilation error shown on several iOS bots, e.g. here: https://build.chromium.org/p/chromium.mac/builders/ios-simulator-xcode-clang/builds/11111/steps/compile/logs/stdio

The following lines:
=====================================================================================================================
../../components/favicon/ios/web_favicon_driver.mm:134:7: error: no matching constructor for initialization of 'image_fetcher::IOSImageDataFetcherWrapper'
      image_fetcher_(web_state->GetBrowserState()->GetRequestContext(),
      ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../components/image_fetcher/ios/ios_image_data_fetcher_wrapper.h:37:3: note: candidate constructor not viable: cannot convert argument of incomplete type 'base::SequencedWorkerPool *' to 'const scoped_refptr<base::TaskRunner>'
  IOSImageDataFetcherWrapper(
  ^
../../components/image_fetcher/ios/ios_image_data_fetcher_wrapper.h:70:28: note: candidate constructor not viable: requires 1 argument, but 2 were provided
  DISALLOW_COPY_AND_ASSIGN(IOSImageDataFetcherWrapper);
=====================================================================================================================

seem to point to this CL.

Although the buildbot failure email pointed to another CL (https://codereview.chromium.org/2690533002/), I think that one is a red herring, and I'll proceed to revert this one.

Original issue's description:
> Use IOSImageDataFetcherWrapper for favicon
>
> Use IOSImageDataFetcher instead of ImageDataFetcher for downloading the favicon
> on iOS. This allows the download to be done in the favicon driver instead of the
> WebState.
> The favicon needs the http response code for optimization (if the favicon does
> not exist we try to download it only once).
>
> BUG=683918
>
> Review-Url: https://codereview.chromium.org/2677993002
> Cr-Commit-Position: refs/heads/master@{#450317}
> Committed: https://chromium.googlesource.com/chromium/src/+/911c2949fcb7a8362449e8af1d60bbb93d3cfab5

TBR=treib@chromium.org,markusheintz@chromium.org,sdefresne@chromium.org,rohitrao@chromium.org,eugenebut@chromium.org,reed@google.com,bsalomon@google.com,gambard@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=683918

Review-Url: https://codereview.chromium.org/2693043003
Cr-Original-Commit-Position: refs/heads/master@{#450323}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 8412e37d0409d43e915a23b87f5cda464bae507a