Revert "Add EG test for Most Visited context menu"
This reverts commit 2da357d03d7ea0cc3831a67fdc22f5ffd04f2b4e.

Reason for revert: It looks like https://chromium-review.googlesource.com/620656 is causing
iOS builds to fail:

https://uberchromegw.corp.google.com/i/chromium.mac/builders/ios-device-xcode-clang/builds/34002

  ios/chrome/browser/ui/content_suggestions/content_suggestions_egtest.mm:80:10: error: no viable conversion from returned value of type 'unique_ptr<net::test_server::BasicHttpResponse>' to function return type 'unique_ptr<net::test_server::HttpResponse>'
  return http_response;

To avoid conflicts two commits will be reverted:

1) 2da357d03d7e
2) b674a6d9e1c8

Original change's description:
> Add EG test for Most Visited context menu
> 
> This CL adds EG tests for the context menu shown when long pressing
> a Most Visited item in Content Suggestions.
> 
> Bug: 749981
> Change-Id: If6fc45f67b6e2362110cfd8e045a972662478ac2
> Reviewed-on: https://chromium-review.googlesource.com/620656
> Commit-Queue: Gauthier Ambard <gambard@chromium.org>
> Reviewed-by: Stepan Khapugin <stkhapugin@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#495558}

TBR=stkhapugin@chromium.org,gambard@chromium.org

Change-Id: I47dc8a4070414b47943b585410249322adfca927
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 749981
Reviewed-on: https://chromium-review.googlesource.com/621586
Reviewed-by: Chris Mumford <cmumford@chromium.org>
Commit-Queue: Chris Mumford <cmumford@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#495590}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: a3bfe9504e5e2c76638366c8c9440e99bf4d42e0