Revert "Add EG test for ContentSuggestions context menu"
This reverts commit b674a6d9e1c8d0bb906163223eea585bdbab74c5.

Reason for revert: Failing on iOS builds (to compile)

https://uberchromegw.corp.google.com/i/chromium.mac/builders/ios-device-xcode-clang/builds/34002

ios/chrome/browser/ui/content_suggestions/content_suggestions_egtest.mm:80:10: error: no viable conversion from returned value of type 'unique_ptr<net::test_server::BasicHttpResponse>' to function return type 'unique_ptr<net::test_server::HttpResponse>'
  return http_response;

Original change's description:
> Add EG test for ContentSuggestions context menu
> 
> This CL adds EG tests for the context menu shown when long pressing
> a Reading List item in Content Suggestions.
> 
> Bug: 749981
> Change-Id: I2815e32ede73c7ba3d9fd114cae2cfd50a58aa87
> Reviewed-on: https://chromium-review.googlesource.com/619151
> Commit-Queue: Gauthier Ambard <gambard@chromium.org>
> Reviewed-by: Olivier Robin <olivierrobin@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#495555}

TBR=olivierrobin@chromium.org,gambard@chromium.org

Change-Id: I27512965e07eed71287319a2fe550cad7da34c81
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 749981
Reviewed-on: https://chromium-review.googlesource.com/621286
Commit-Queue: Chris Mumford <cmumford@chromium.org>
Reviewed-by: Chris Mumford <cmumford@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#495592}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: fc9f74b941603a96d466e533bd52fbcbbfb0bcb0