Reland of (Set)IsOverridingUserAgent should be called on VisibleItem (patchset #9 id:180001 of https://codereview.chromium.org/2711683002/ )
Reason for reland:
Fixed the bugs.

Original issues description:
Revert of (Set)IsOverridingUserAgent should be called on VisibleItem (patchset #9 id:180001 of https://codereview.chromium.org/2711683002/ )

Reason for revert:
Causes ToolsPopupMenuTestCase.testToolsMenuRequestDesktopNetwork to fail with error:
../../ios/chrome/browser/ui/tools_menu/tools_popup_menu_egtest.mm:109: error: -[ToolsPopupMenuTestCase testToolsMenuRequestDesktopNetwork] : Exception: NoMatchingElementException

Original issue's description:
> (Set)IsOverridingUserAgent should be called on VisibleItem
>
> As explained in the associated bug, it always makes sense to call
> IsOverridingUserAgent() and SetIsOverridingUserAgent() on visible item
> instead of current item. Thus this CL changes CurrentItem to VisibleItem
> wherever necessary.
>
> Besides, this CL also does the following refactoring to have
> NavigationManagerImpl encapsulate VisibleItem for calling
> (Set)IsOverridingUserAgent() to provide one more layer of abstraction.
>
> BUG=693794
>
> Review-Url: https://codereview.chromium.org/2711683002
> Cr-Commit-Position: refs/heads/master@{#452570}
> Committed: https://chromium.googlesource.com/chromium/src/+/21359189a7883d38a531e8681cc250bdf301fa85

TBR=eugenebut@chromium.org,kkhorimoto@chromium.org,liaoyuke@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=693794
Review-Url: https://codereview.chromium.org/2711733007
Cr-Commit-Position: refs/heads/master@{#452713}
Committed: https://chromium.googlesource.com/chromium/src/+/55a8e3f7414855960a20135217d32de930466f3d

BUG=

Review-Url: https://codereview.chromium.org/2710593010
Cr-Original-Commit-Position: refs/heads/master@{#452945}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: b8453e1f8d0bd721540c5d4741f3b75e782eaf1d